(* $Id: keys.qwerty.def,v 1.23 2005/10/06 20:09:56 ddr Exp $ *)

let _SHIFT x = Char.chr (Char.code x + Char.code 'A' - Char.code 'a')

let _CTRL x = Char.chr (Char.code x - (Char.code 'a' - 1))

let _ROGUE_KEY_NORTH = 'k'
let _ROGUE_KEY_SOUTH = 'j'
let _ROGUE_KEY_EAST = 'l'
let _ROGUE_KEY_WEST = 'h'
let _ROGUE_KEY_NORTHEAST = 'u'
let _ROGUE_KEY_NORTHWEST = 'y'
let _ROGUE_KEY_SOUTHEAST = 'n'
let _ROGUE_KEY_SOUTHWEST = 'b'

let _ROGUE_KEY_NORTH_SHIFT = _SHIFT _ROGUE_KEY_NORTH
let _ROGUE_KEY_SOUTH_SHIFT = _SHIFT _ROGUE_KEY_SOUTH
let _ROGUE_KEY_EAST_SHIFT = _SHIFT _ROGUE_KEY_EAST
let _ROGUE_KEY_WEST_SHIFT = _SHIFT _ROGUE_KEY_WEST
let _ROGUE_KEY_NORTHEAST_SHIFT = _SHIFT _ROGUE_KEY_NORTHEAST
let _ROGUE_KEY_NORTHWEST_SHIFT = _SHIFT _ROGUE_KEY_NORTHWEST
let _ROGUE_KEY_SOUTHEAST_SHIFT = _SHIFT _ROGUE_KEY_SOUTHEAST
let _ROGUE_KEY_SOUTHWEST_SHIFT = _SHIFT _ROGUE_KEY_SOUTHWEST

let _ROGUE_KEY_NORTH_CTRL = _CTRL _ROGUE_KEY_NORTH
let _ROGUE_KEY_SOUTH_CTRL = _CTRL _ROGUE_KEY_SOUTH
let _ROGUE_KEY_EAST_CTRL = _CTRL _ROGUE_KEY_EAST
let _ROGUE_KEY_WEST_CTRL = _CTRL _ROGUE_KEY_WEST
let _ROGUE_KEY_NORTHEAST_CTRL = _CTRL _ROGUE_KEY_NORTHEAST
let _ROGUE_KEY_NORTHWEST_CTRL = _CTRL _ROGUE_KEY_NORTHWEST
let _ROGUE_KEY_SOUTHEAST_CTRL = _CTRL _ROGUE_KEY_SOUTHEAST
let _ROGUE_KEY_SOUTHWEST_CTRL = _CTRL _ROGUE_KEY_SOUTHWEST

let _ROGUE_KEY_INSTRUCTIONS = '?'
let _ROGUE_KEY_REST = '.'
let _ROGUE_KEY_SEARCH = 's'
let _ROGUE_KEY_INVENTORY = 'i'
let _ROGUE_KEY_FIGHT = 'f'
let _ROGUE_KEY_FIGHT_TO_DEATH = 'F'
let _ROGUE_KEY_EAT = 'e'
let _ROGUE_KEY_QUAFF = 'q'
let _ROGUE_KEY_READ = 'r'
let _ROGUE_KEY_MOVE = 'm'
let _ROGUE_KEY_DROP = 'd'
let _ROGUE_KEY_PUT_ON_RING = 'P'
let _ROGUE_KEY_REMOVE_RING = 'R'
let _ROGUE_KEY_DROP_CHECK = '>'
let _ROGUE_KEY_CHECK_UP = '<'
let _ROGUE_KEY_INV_WEAPON = ')'
let _ROGUE_KEY_INV_ARMOR = ']'
let _ROGUE_KEY_INV_RINGS = '='
let _ROGUE_KEY_ID_TRAP = '^'
let _ROGUE_KEY_SINGLE_INV = 'I'
let _ROGUE_KEY_DISCOVERED = 'D'
let _ROGUE_KEY_TAKE_OFF = 'T'
let _ROGUE_KEY_WEAR = 'W'
let _ROGUE_KEY_WIELD = 'w'
let _ROGUE_KEY_CALL = 'c'
let _ROGUE_KEY_ZAPP = 'z'
let _ROGUE_KEY_THROW = 't'
let _ROGUE_KEY_PICK_UP = ','
let _ROGUE_KEY_CHANGE_LANG = '@'

let _ROGUE_KEY_REMESSAGE = _CTRL 'p'
let _ROGUE_KEY_VERSION = 'v'
let _ROGUE_KEY_QUIT = 'Q'
let _ROGUE_KEY_SAVE_GAME = 'S'
let _ROGUE_KEY_WHATISIT = '/'
let _ROGUE_KEY_NOP = ' '

let _ROGUE_KEY_CANCEL = '\027'
let _ROGUE_KEY_LIST = '*'
let _ROGUE_KEY_SAVE_SCREEN = 'X'
let _ROGUE_KEY_REFRESH = _CTRL 'r'

let _ROGUE_KEY_WIZARDIZE = _CTRL 'w'
let _ROGUE_KEY_WIZ_INVENTORY = _CTRL 'i'
let _ROGUE_KEY_WIZ_MAGIC_MAP = _CTRL 's'
let _ROGUE_KEY_WIZ_SHOW_TRAPS = _CTRL 't'
let _ROGUE_KEY_WIZ_SHOW_OBJS = _CTRL 'o'
let _ROGUE_KEY_SHOW_AV_HP = _CTRL 'a'
let _ROGUE_KEY_WIZ_NEW_OBJ = '\127'
let _ROGUE_KEY_WIZ_SHOW_MONST = _CTRL 'm'
